#!/bin/bash
echo "正在获取帮助..."
echo ""
echo ""

echo "📚 Claude Code PM - 项目管理系统"
echo "============================================="
echo ""
echo "🎯 快速开始工作流"
echo "  1. /pm:prd-new <name>        - Create a new PRD"
echo "  2. /pm:prd-parse <name>      - Convert PRD to epic"
echo "  3. /pm:epic-decompose <name> - Break into tasks"
echo "  4. /pm:epic-sync <name>      - Push to GitHub"
echo "  5. /pm:epic-start <name>     - Start parallel execution"
echo ""
echo "📄 PRD 命令"
echo "  /pm:prd-new <name>     - Launch brainstorming for new product requirement"
echo "  /pm:prd-parse <name>   - Convert PRD to implementation epic"
echo "  /pm:prd-list           - List all PRDs"
echo "  /pm:prd-edit <name>    - Edit existing PRD"
echo "  /pm:prd-status         - Show PRD implementation status"
echo ""
echo "📚 史诗命令"
echo "  /pm:epic-decompose <name> - Break epic into task files"
echo "  /pm:epic-sync <name>      - Push epic and tasks to GitHub"
echo "  /pm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /pm:epic-list             - List all epics"
echo "  /pm:epic-show <name>      - Display epic and its tasks"
echo "  /pm:epic-status [name]    - Show epic progress"
echo "  /pm:epic-close <name>     - Mark epic as complete"
echo "  /pm:epic-edit <name>      - Edit epic details"
echo "  /pm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /pm:epic-start <name>     - Launch parallel agent execution"
echo ""
echo "📝 问题命令"
echo "  /pm:issue-show <num>      - Display issue and sub-issues"
echo "  /pm:issue-status <num>    - Check issue status"
echo "  /pm:issue-start <num>     - Begin work with specialized agent"
echo "  /pm:issue-sync <num>      - Push updates to GitHub"
echo "  /pm:issue-close <num>     - Mark issue as complete"
echo "  /pm:issue-reopen <num>    - Reopen closed issue"
echo "  /pm:issue-edit <num>      - Edit issue details"
echo "  /pm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "🔄 工作流命令"
echo "  /pm:next               - Show next priority tasks"
echo "  /pm:status             - Overall project dashboard"
echo "  /pm:standup            - Daily standup report"
echo "  /pm:blocked            - Show blocked tasks"
echo "  /pm:in-progress        - List work in progress"
echo ""
echo "🔗 同步命令"
echo "  /pm:sync               - Full bidirectional sync with GitHub"
echo "  /pm:import <issue>     - Import existing GitHub issues"
echo ""
echo "🔧 维护命令"
echo "  /pm:validate           - Check system integrity"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search across all content"
echo ""
echo "⚙️  设置命令"
echo "  /pm:init               - Install dependencies and configure GitHub"
echo "  /pm:help               - Show this help message"
echo ""
echo "💡 提示"
echo "  • Use /pm:next to find available work"
echo "  • Run /pm:status for quick overview"
echo "  • Epic workflow: prd-new → prd-parse → epic-decompose → epic-sync"
echo "  • View README.md for complete documentation"

exit 0
